version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - bodyclose
    - noctx

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
